from enum import Enum


# TODO: Change to syntactic folder
class States(Enum):
    NOT = 43
    NOT_EQUAL = 34
    AND = 28
    LEFT_PARENTHESIS = 26
    RIGHT_PARENTHESIS = 27
    TIMES = 40
    PLUS = 36
    PLUS_PLUS = 37
    COMMA = 20
    MINUS = 38
    MINUS_MINUS = 39
    DOT = 42
    DIVIDE = 41
    COLON = 18
    SEMI_COLON = 19
    LESS_THAN = 30
    LESS_OR_EQUAL = 32
    EQUALS = 21
    EQUAL_EQUAL = 35
    GREATER_THAN = 31
    GREATER_OR_EQUAL = 33
    LEFT_SQUARE = 22
    RIGHT_SQUARE = 23
    ARRAY = 0
    BOOLEAN = 1
    BREAK = 2
    CHAR = 3
    CONTINUE = 4
    DO = 5
    ELSE = 6
    FUNCTION = 8
    ID = 47
    IF = 9
    INTEGER = 10
    OF = 11
    STRING = 12
    STRUCT = 13
    TYPE = 15
    VAR = 16
    WHILE = 17
    LEFT_BRACES = 24
    OR = 29
    RIGHT_BRACES = 25
    EOF = 49
    CHR = 44
    FALSE = 7
    NUM = 45
    STR = 46
    TRUE = 14
    UNKNOWN = 48
    DC = 56
    DE = 52
    DF = 53
    DT = 54
    DV = 62
    E = 64
    F = 69
    IDD = 80
    IDU = 81
    L = 66
    LDE = 51
    LDV = 60
    LE = 70
    LI = 57
    LP = 58
    LS = 61
    LV = 65
    P = 50
    R = 67
    S = 63
    T = 55
    Y = 68
    C = 82
    N = 83
    s = 84
    true = 85
    false = 86
    B = 59
    MC = 87
    MF = 88
    NB = 89
    NF = 90
    id = 91


class Kinds(Enum):
    NO_KIND_DEF_ = -1
    VAR_ = 0
    PARAM_ = 1
    FUNCTION_ = 2
    FIELD_ = 3
    ARRAY_TYPE_ = 4
    STRUCT_TYPE_ = 5
    ALIAS_TYPE_ = 6
    SCALAR_TYPE_ = 7
    UNIVERSAL_ = 8


class Errors(Enum):
    ERR_REDECL = 0  #ok
    ERR_NOT_DECL = 1  #ok
    ERR_TYPE_EXPECTED = 2  #ok
    ERR_BOOL_TYPE_EXPECTED = 3
    ERR_TYPE_MISMATCH = 4
    ERR_INVALID_TYPE = 5
    ERR_KIND_NOT_STRUCT = 6
    ERR_FIELD_NOT_DECL = 7
    ERR_KIND_NOT_ARRAY = 8
    ERR_INVALID_INDEX_TYPE = 9
    ERR_KIND_NOT_VAR = 10
    ERR_KIND_NOT_FUNCTION = 11
    ERR_TOO_MANY_ARG = 12
    ERR_PARAM_TYPE = 13
    ERR_TOO_FEW_ARGS = 14
    ERR_RETURN_TYPE_MISMATCH = 15


class SemanticRules(Enum):
    IDD_RULE = 30
    IDU_RULE = 31
    ID_RULE = 30
    NB_RULE = 57
    DT_STRUCT_RULE = 9
    DF_RULE = 7
    T_INTEGER_RULE = 68
    T_CHAR_RULE = 69
    T_BOOL_RULE = 70
    T_STRING_RULE = 71
    T_IDU_RULE = 72
    LI_IDD_RULE = 46
    LI_LI_IDD_RULE = 45
    DV_RULE = 11
    TRUE_RULE = 73
    FALSE_RULE = 29
    CHR_RULE = 2
    STR_RULE = 67
    NUM_RULE = 54
    DT_ARRAY_RULE = 8
    DT_IDD_RULE = 10
    DC_DC_LI_RULE = 4
    DC_DC_LI_T_RULE = 3
    LP_IDD_RULE = 48
    LP_LP_IDD_RULE = 47
    MF_RULE = 56
